[package]
name = "neuronguard"
version = "0.1.0"
edition = "2021"
default-run = "llm-router"

[dependencies]
crossbeam-channel = "0.5"
rand = "0.8"
csv = "1.1"
pyo3 = { version = "0.21", features = ["experimental-declarative-modules"] }

[features]
extension-module = ["pyo3/extension-module"]

[lib]
name = "neuronguard"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "neuron-poc"
path = "src/main.rs"

[[bin]]
name = "llm-router"
path = "example/llm_router/main.rs"

[[bin]]
name = "ag-news"
path = "example/ag_news/main.rs"

[[bin]]
name = "dbpedia"
path = "example/dbpedia/main.rs"
