[package]
name = "neuron-poc"
version = "0.1.0"
edition = "2021"
default-run = "llm-router"

[dependencies]
crossbeam-channel = "0.5"
rand = "0.8"
csv = "1.1"

[lib]
name = "neuron_poc"
path = "src/lib.rs"

[[bin]]
name = "neuron-poc"
path = "src/main.rs"

[[bin]]
name = "llm-router"
path = "example/llm_router/main.rs"

[[bin]]
name = "ag-news"
path = "example/ag_news/main.rs"

[[bin]]
name = "dbpedia"
path = "example/dbpedia/main.rs"
