[tools]
rust = "latest"

[tasks.poc]
run = "cargo run --bin neuron-poc"

[tasks.llm_router]
run = "cargo run --bin llm-router"

[tasks.ag_news]
run = "cargo run --bin ag-news"

[tasks.run]
run = "cargo run"

[tasks.test]
run = "cargo test"
